/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup_form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DBSS075
 */
public class Gaji_data extends javax.swing.JFrame {

    /**
     * Creates new form Gaji_data
     */
    Connection con= null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Gaji_data() {
        initComponents();
        show_gaji();
    }
    public ArrayList<Gaji> gaji(){
        ArrayList<Gaji> gaji = new ArrayList<>();
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url); 
            String queryl = " SELECT * FROM gaji";
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(queryl);
            Gaji gaji_karyawan;
            while(rs.next()){
                gaji_karyawan = new Gaji(rs.getString("nama"), rs.getString("jabatan")
                        ,rs.getInt("gaji_pokok"), rs.getInt("tunjangan"), rs.getString("id_karyawan"));
                gaji.add(gaji_karyawan);
            }
         }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         return gaji;
    } 
    public  void show_gaji(){
        ArrayList<Gaji> gaji_list = gaji();
        DefaultTableModel model = (DefaultTableModel )tabel_gaji.getModel(); 
        Object[] row = new Object[5];
        for (int i = 0; i < gaji_list.size(); i++) {
            row[0]= gaji_list.get(i).getNama();
            row[1]= gaji_list.get(i).getJabatan();
            row[2]= gaji_list.get(i).getGaji_pokok();
            row[3]= gaji_list.get(i).getTunjangan();
            row[4]= gaji_list.get(i).getId_karyawan();
            model.addRow(row);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jabatan = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        nama_obat = new javax.swing.JLabel();
        gajipokok = new javax.swing.JLabel();
        tunjangan = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        reset_gaji = new javax.swing.JButton();
        input_gaji = new javax.swing.JButton();
        id_karyawan = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Karyawan = new javax.swing.JButton();
        Supplier = new javax.swing.JButton();
        Konsumen = new javax.swing.JButton();
        Obat = new javax.swing.JButton();
        ResepDokter = new javax.swing.JButton();
        FakturPenjualan = new javax.swing.JButton();
        Cabang = new javax.swing.JButton();
        Gaji = new javax.swing.JButton();
        Jabatan = new javax.swing.JButton();
        Tanggungan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gaji = new javax.swing.JTable();
        jabatan1 = new javax.swing.JPanel();
        nama1 = new javax.swing.JLabel();
        nama_obat1 = new javax.swing.JLabel();
        gajipokok1 = new javax.swing.JLabel();
        tunjangan1 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        search_gaji = new javax.swing.JButton();
        update_gaji = new javax.swing.JButton();
        id_karyawan1 = new javax.swing.JLabel();
        txt10 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        delete_gaji = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jabatan.setBackground(new java.awt.Color(36, 47, 65));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(204, 204, 204));
        nama.setText("Nama");

        nama_obat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_obat.setForeground(new java.awt.Color(204, 204, 204));
        nama_obat.setText("Jabatan");

        gajipokok.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gajipokok.setForeground(new java.awt.Color(204, 204, 204));
        gajipokok.setText("Gaji Pokok");

        tunjangan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tunjangan.setForeground(new java.awt.Color(204, 204, 204));
        tunjangan.setText("Tunjangan");

        txt1.setBackground(new java.awt.Color(36, 47, 65));
        txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(204, 204, 204));
        txt1.setText("Enter Nama");
        txt1.setBorder(null);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(36, 47, 65));
        txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(204, 204, 204));
        txt2.setText("Enter Jabatan");
        txt2.setBorder(null);
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });

        txt3.setBackground(new java.awt.Color(36, 47, 65));
        txt3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(204, 204, 204));
        txt3.setText("Enter Gaji Pokok");
        txt3.setBorder(null);
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });

        txt4.setEditable(false);
        txt4.setBackground(new java.awt.Color(36, 47, 65));
        txt4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt4.setForeground(new java.awt.Color(204, 204, 204));
        txt4.setText("Entrer Tunjangan");
        txt4.setBorder(null);
        txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt4MouseClicked(evt);
            }
        });
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Input Data Gaji");

        reset_gaji.setBackground(new java.awt.Color(97, 212, 195));
        reset_gaji.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset_gaji.setText("Reset");
        reset_gaji.setBorder(null);
        reset_gaji.setBorderPainted(false);
        reset_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_gajiActionPerformed(evt);
            }
        });

        input_gaji.setBackground(new java.awt.Color(97, 212, 195));
        input_gaji.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        input_gaji.setText("Input");
        input_gaji.setBorder(null);
        input_gaji.setBorderPainted(false);
        input_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_gajiActionPerformed(evt);
            }
        });

        id_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_karyawan.setForeground(new java.awt.Color(204, 204, 204));
        id_karyawan.setText("ID Karyawan");

        txt5.setBackground(new java.awt.Color(36, 47, 65));
        txt5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt5.setForeground(new java.awt.Color(204, 204, 204));
        txt5.setText("Enter ID Karyawan");
        txt5.setBorder(null);
        txt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt5MouseClicked(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jabatanLayout = new javax.swing.GroupLayout(jabatan);
        jabatan.setLayout(jabatanLayout);
        jabatanLayout.setHorizontalGroup(
            jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatanLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jabatanLayout.createSequentialGroup()
                        .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jabatanLayout.createSequentialGroup()
                                .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jabatanLayout.createSequentialGroup()
                                        .addComponent(input_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reset_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jabatanLayout.createSequentialGroup()
                                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama_obat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tunjangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gajipokok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt3)
                                    .addComponent(txt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jabatanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jabatanLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jabatanLayout.setVerticalGroup(
            jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatanLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_obat)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajipokok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tunjangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karyawan))
                .addGap(3, 3, 3)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        Home.setBackground(new java.awt.Color(0, 204, 255));
        Home.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/avatar (1).png"))); // NOI18N
        Home.setText(" Admin Profile");
        Home.setBorder(null);
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Karyawan.setBackground(new java.awt.Color(0, 204, 255));
        Karyawan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/employees (1).png"))); // NOI18N
        Karyawan.setText("Karyawan");
        Karyawan.setBorderPainted(false);
        Karyawan.setContentAreaFilled(false);
        Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaryawanActionPerformed(evt);
            }
        });

        Supplier.setBackground(new java.awt.Color(0, 204, 255));
        Supplier.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hotel-supplier (1).png"))); // NOI18N
        Supplier.setText("Supplier");
        Supplier.setBorderPainted(false);
        Supplier.setContentAreaFilled(false);
        Supplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        Konsumen.setBackground(new java.awt.Color(0, 204, 255));
        Konsumen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Konsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/people (1).png"))); // NOI18N
        Konsumen.setText("Konsumen");
        Konsumen.setBorderPainted(false);
        Konsumen.setContentAreaFilled(false);
        Konsumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Konsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonsumenActionPerformed(evt);
            }
        });

        Obat.setBackground(new java.awt.Color(0, 204, 255));
        Obat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/tablet-and-pill (1).png"))); // NOI18N
        Obat.setText("Obat");
        Obat.setBorderPainted(false);
        Obat.setContentAreaFilled(false);
        Obat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        ResepDokter.setBackground(new java.awt.Color(0, 204, 255));
        ResepDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ResepDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/approve-invoice (1).png"))); // NOI18N
        ResepDokter.setText("Resep Dokter");
        ResepDokter.setBorderPainted(false);
        ResepDokter.setContentAreaFilled(false);
        ResepDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ResepDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResepDokterActionPerformed(evt);
            }
        });

        FakturPenjualan.setBackground(new java.awt.Color(0, 204, 255));
        FakturPenjualan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FakturPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/invoice.png"))); // NOI18N
        FakturPenjualan.setText("Faktur Penjualan");
        FakturPenjualan.setBorderPainted(false);
        FakturPenjualan.setContentAreaFilled(false);
        FakturPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FakturPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakturPenjualanActionPerformed(evt);
            }
        });

        Cabang.setBackground(new java.awt.Color(0, 204, 255));
        Cabang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cabang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/pharmacy (1).png"))); // NOI18N
        Cabang.setText("Cabang");
        Cabang.setBorderPainted(false);
        Cabang.setContentAreaFilled(false);
        Cabang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CabangActionPerformed(evt);
            }
        });

        Gaji.setBackground(new java.awt.Color(0, 204, 255));
        Gaji.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/money (1).png"))); // NOI18N
        Gaji.setText("Gaji");
        Gaji.setBorderPainted(false);
        Gaji.setContentAreaFilled(false);
        Gaji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GajiActionPerformed(evt);
            }
        });

        Jabatan.setBackground(new java.awt.Color(0, 204, 255));
        Jabatan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Jabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/manager (1).png"))); // NOI18N
        Jabatan.setText("Jabatan");
        Jabatan.setBorderPainted(false);
        Jabatan.setContentAreaFilled(false);
        Jabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabatanActionPerformed(evt);
            }
        });

        Tanggungan.setBackground(new java.awt.Color(0, 204, 255));
        Tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Tanggungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/users (1).png"))); // NOI18N
        Tanggungan.setText("Tanggungan");
        Tanggungan.setBorderPainted(false);
        Tanggungan.setContentAreaFilled(false);
        Tanggungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggunganActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/medicine (1).png"))); // NOI18N
        jLabel2.setText("Pharmacy");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Konsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResepDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FakturPenjualan)
                            .addComponent(Cabang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Karyawan)
                .addGap(18, 18, 18)
                .addComponent(Supplier)
                .addGap(18, 18, 18)
                .addComponent(Konsumen)
                .addGap(18, 18, 18)
                .addComponent(Obat)
                .addGap(18, 18, 18)
                .addComponent(ResepDokter)
                .addGap(18, 18, 18)
                .addComponent(FakturPenjualan)
                .addGap(18, 18, 18)
                .addComponent(Cabang)
                .addGap(18, 18, 18)
                .addComponent(Gaji)
                .addGap(18, 18, 18)
                .addComponent(Jabatan)
                .addGap(18, 18, 18)
                .addComponent(Tanggungan)
                .addGap(88, 88, 88))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(691, Short.MAX_VALUE)))
        );

        tabel_gaji.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabel_gaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jabatan", "Gaji Pokok", "Tunjangan", "ID Karyawan"
            }
        ));
        tabel_gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_gajiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_gaji);

        jabatan1.setBackground(new java.awt.Color(36, 47, 65));

        nama1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama1.setForeground(new java.awt.Color(204, 204, 204));
        nama1.setText("Nama");

        nama_obat1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_obat1.setForeground(new java.awt.Color(204, 204, 204));
        nama_obat1.setText("Jabatan");

        gajipokok1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gajipokok1.setForeground(new java.awt.Color(204, 204, 204));
        gajipokok1.setText("Gaji Pokok");

        tunjangan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tunjangan1.setForeground(new java.awt.Color(204, 204, 204));
        tunjangan1.setText("Tunjangan");

        txt6.setBackground(new java.awt.Color(36, 47, 65));
        txt6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt6.setForeground(new java.awt.Color(204, 204, 204));
        txt6.setText("Enter Nama");
        txt6.setBorder(null);
        txt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt6MouseClicked(evt);
            }
        });

        txt7.setBackground(new java.awt.Color(36, 47, 65));
        txt7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt7.setForeground(new java.awt.Color(204, 204, 204));
        txt7.setBorder(null);

        txt8.setBackground(new java.awt.Color(36, 47, 65));
        txt8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt8.setForeground(new java.awt.Color(204, 204, 204));
        txt8.setBorder(null);

        txt9.setBackground(new java.awt.Color(36, 47, 65));
        txt9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt9.setForeground(new java.awt.Color(204, 204, 204));
        txt9.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Data Gaji");

        search_gaji.setBackground(new java.awt.Color(97, 212, 195));
        search_gaji.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search_gaji.setText("Search");
        search_gaji.setBorder(null);
        search_gaji.setBorderPainted(false);
        search_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_gajiActionPerformed(evt);
            }
        });

        update_gaji.setBackground(new java.awt.Color(97, 212, 195));
        update_gaji.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update_gaji.setText("Update");
        update_gaji.setBorder(null);
        update_gaji.setBorderPainted(false);
        update_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_gajiActionPerformed(evt);
            }
        });

        id_karyawan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_karyawan1.setForeground(new java.awt.Color(204, 204, 204));
        id_karyawan1.setText("ID Karyawan");

        txt10.setBackground(new java.awt.Color(36, 47, 65));
        txt10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt10.setForeground(new java.awt.Color(204, 204, 204));
        txt10.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        delete_gaji.setBackground(new java.awt.Color(97, 212, 195));
        delete_gaji.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delete_gaji.setText("Delete");
        delete_gaji.setBorder(null);
        delete_gaji.setBorderPainted(false);
        delete_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_gajiActionPerformed(evt);
            }
        });

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jabatan1Layout = new javax.swing.GroupLayout(jabatan1);
        jabatan1.setLayout(jabatan1Layout);
        jabatan1Layout.setHorizontalGroup(
            jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatan1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel3)
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jabatan1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jabatan1Layout.createSequentialGroup()
                        .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_karyawan1)
                            .addComponent(tunjangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gajipokok1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_obat1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jabatan1Layout.createSequentialGroup()
                                .addComponent(update_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator10)
                            .addComponent(jSeparator11)
                            .addComponent(jSeparator12)
                            .addComponent(jSeparator13))))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jabatan1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14)
                    .addComponent(txt6))
                .addGap(33, 33, 33)
                .addComponent(search_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jabatan1Layout.setVerticalGroup(
            jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatan1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_gaji, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_obat1))
                .addGap(3, 3, 3)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajipokok1))
                .addGap(5, 5, 5)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tunjangan1))
                .addGap(4, 4, 4)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karyawan1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jabatan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jabatan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jabatan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_gajiActionPerformed
        // TODO add your handling code here:
        txt1.setText(null);
        txt2.setText(null);
        txt3.setText(null);
        txt4.setText(null);
        txt5.setText(null);
       
    }//GEN-LAST:event_reset_gajiActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home hh = new Home();
        try {
            this.dispose();
            hh.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanActionPerformed
        // TODO add your handling code here:
        Karyawan_data kd= new Karyawan_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KaryawanActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        // TODO add your handling code here:
         Supplier_data sd = new Supplier_data();
        try {
            this.dispose();
            sd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SupplierActionPerformed

    private void KonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonsumenActionPerformed
        // TODO add your handling code here:
        Konsumen_data kd = new Konsumen_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KonsumenActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
        // TODO add your handling code here:
        Obat_data od = new Obat_data();
        try {
            this.dispose();
            od.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ObatActionPerformed

    private void ResepDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResepDokterActionPerformed
        // TODO add your handling code here:
         ResepDokter_data rd = new ResepDokter_data();
        try {
            this.dispose();
            rd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ResepDokterActionPerformed

    private void FakturPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakturPenjualanActionPerformed
        // TODO add your handling code here:
        FakturPenjualan_data fd = new FakturPenjualan_data();
        try {
            this.dispose();
            fd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_FakturPenjualanActionPerformed

    private void CabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CabangActionPerformed
        // TODO add your handling code here:
        Cabang_data cd = new Cabang_data();
        try {
            this.dispose();
            cd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CabangActionPerformed

    private void GajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GajiActionPerformed
        // TODO add your handling code here:
        Gaji_data gd = new Gaji_data();
        try {
            this.dispose();
            gd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GajiActionPerformed

    private void JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabatanActionPerformed
        // TODO add your handling code here:
        Jabatan_data jd = new Jabatan_data();
        try {
            this.dispose();
            jd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JabatanActionPerformed

    private void TanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggunganActionPerformed
        // TODO add your handling code here:
        Tanggungan_data td = new Tanggungan_data();
        try {
            this.dispose();
            td.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_TanggunganActionPerformed

    private void search_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_gajiActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(" SELECT * FROM gaji WHERE nama = '"+ txt6.getText()+"'"); 
            if (rs.next()){
                String i = txt6.getText();
                String a = rs.getString("jabatan");
                String b = rs.getString("gaji_pokok");
                String c = rs.getString("tunjangan");
                String d = rs.getString("id_karyawan");
                txt7.setText(a);
                txt8.setText(b);
                txt9.setText(c);
                txt10.setText(d);
                txt6.getText();
            } else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Invalid Nama");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_search_gajiActionPerformed

    private void delete_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_gajiActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("delete gaji WHERE id_karyawan = "+ txt6.getText());
            txt7.setText(null);
                txt8.setText(null);
                txt9.setText(null);
                txt10.setText(null);
                txt6.setText(null);
            DefaultTableModel model = (DefaultTableModel)tabel_gaji.getModel();
            model.setRowCount(0);
            show_gaji();
                JOptionPane.showMessageDialog(null, "Data Deleted");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_delete_gajiActionPerformed

    private void input_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_gajiActionPerformed
        // TODO add your handling code here:
        String a = txt1.getText();
        String b = txt2.getText();
        String c = txt3.getText();
        String d = txt4.getText();
        String f = txt5.getText();
       
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            String sql = " insert into faktur_penjualan(nama,jabatan,gaji_pokok,tunjangan,id_karyawan) values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txt1.getText());
            pst.setString(2, txt2.getText());
            pst.setString(3, txt3.getText());
            pst.setString(4, txt4.getText());
            pst.setString(5, txt5.getText());
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)tabel_gaji.getModel();
            model.setRowCount(0);
            show_gaji();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertion Failed");
        }
    }//GEN-LAST:event_input_gajiActionPerformed

    private void update_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_gajiActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("update gaji set jabatan = '"+txt7.getText()+
                     "',gaji_pokok = '"+txt8.getText()+
                     "',tunjangan = '"+txt9.getText()+
                     "',id_karyawan = '"+txt10.getText()+
                     "' WHERE nama = '"+txt6.getText()+"'");             
             if(rs.next()){                
               String i = txt6.getText();
               String a = rs.getString("jabatan");
                String b = rs.getString("gaji_pokok");
                String c = rs.getString("tunjangan");
                String d = rs.getString("id_karyawan");
                txt7.setText(a);
                txt8.setText(b);
                txt9.setText(c);
                txt10.setText(d);
                txt6.getText();                
             }            
            DefaultTableModel model = (DefaultTableModel)tabel_gaji.getModel();
            model.setRowCount(0);
            show_gaji();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Updated"); 
        }
    }//GEN-LAST:event_update_gajiActionPerformed

    private void tabel_gajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_gajiMouseClicked
        // TODO add your handling code here:
        int i = tabel_gaji.getSelectedRow();
        TableModel model = tabel_gaji.getModel();
        txt6.setText(model.getValueAt(i,0).toString());
        txt7.setText(model.getValueAt(i,1).toString());
        txt8.setText(model.getValueAt(i,2).toString());
        txt9.setText(model.getValueAt(i,3).toString());
        txt10.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_tabel_gajiMouseClicked

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        // TODO add your handling code here:
        txt1.setText("");
    }//GEN-LAST:event_txt1MouseClicked

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        // TODO add your handling code here:
        txt2.setText("");
    }//GEN-LAST:event_txt2MouseClicked

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        // TODO add your handling code here:
        txt3.setText("");
    }//GEN-LAST:event_txt3MouseClicked

    private void txt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MouseClicked
        // TODO add your handling code here:
        txt4.setText("");
    }//GEN-LAST:event_txt4MouseClicked

    private void txt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt5MouseClicked
        // TODO add your handling code here:
        txt5.setText("");
    }//GEN-LAST:event_txt5MouseClicked

    private void txt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt6MouseClicked
        // TODO add your handling code here:
        txt6.setText("");
    }//GEN-LAST:event_txt6MouseClicked

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gaji_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gaji_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gaji_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gaji_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gaji_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cabang;
    private javax.swing.JButton FakturPenjualan;
    private javax.swing.JButton Gaji;
    private javax.swing.JButton Home;
    private javax.swing.JButton Jabatan;
    private javax.swing.JButton Karyawan;
    private javax.swing.JButton Konsumen;
    private javax.swing.JButton Obat;
    private javax.swing.JButton ResepDokter;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton Tanggungan;
    private javax.swing.JButton delete_gaji;
    private javax.swing.JLabel gajipokok;
    private javax.swing.JLabel gajipokok1;
    private javax.swing.JLabel id_karyawan;
    private javax.swing.JLabel id_karyawan1;
    private javax.swing.JButton input_gaji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel jabatan;
    private javax.swing.JPanel jabatan1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama_obat;
    private javax.swing.JLabel nama_obat1;
    private javax.swing.JButton reset_gaji;
    private javax.swing.JButton search_gaji;
    private javax.swing.JTable tabel_gaji;
    private javax.swing.JLabel tunjangan;
    private javax.swing.JLabel tunjangan1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JButton update_gaji;
    // End of variables declaration//GEN-END:variables
}
