/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup_form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DBSS075
 */
public class Jabatan_data extends javax.swing.JFrame {

    /**
     * Creates new form Jabatan_data
     */
    Connection con= null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Jabatan_data() {
        initComponents();
        show_jabatan();
    }
    public ArrayList<Jabatan> jabatan(){
        ArrayList<Jabatan> jabatans = new ArrayList<>();
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url); 
            String queryl = " SELECT * FROM jabatan";
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(queryl);
            Jabatan jabatan;
            while(rs.next()){
                jabatan = new Jabatan(rs.getString("id_krw"),rs.getString("jabatan"));
                jabatans.add(jabatan);
            }
         }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         return jabatans;
    } 
    public  void show_jabatan(){
        ArrayList<Jabatan> jabatan_list = jabatan();
        DefaultTableModel model = (DefaultTableModel )tabel_jabatan.getModel(); 
        Object[] row = new Object[2];
        for (int i = 0; i < jabatan_list.size(); i++) {
            row[0]= jabatan_list.get(i).getId_krw();
            row[1]= jabatan_list.get(i).getJabatan();                      
            model.addRow(row);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Karyawan = new javax.swing.JButton();
        Supplier = new javax.swing.JButton();
        Konsumen = new javax.swing.JButton();
        Obat = new javax.swing.JButton();
        ResepDokter = new javax.swing.JButton();
        FakturPenjualan = new javax.swing.JButton();
        Cabang = new javax.swing.JButton();
        Gaji = new javax.swing.JButton();
        Jabatan = new javax.swing.JButton();
        Tanggungan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        no_cabang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama_cabang = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        reset_jabatan = new javax.swing.JButton();
        input_jabatan = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        no_cabang1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nama_cabang1 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        search_jabatan = new javax.swing.JButton();
        update_jabatan = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        delete_jabatan = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_jabatan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        Home.setBackground(new java.awt.Color(0, 204, 255));
        Home.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/avatar (1).png"))); // NOI18N
        Home.setText(" Admin Profile");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Karyawan.setBackground(new java.awt.Color(0, 204, 255));
        Karyawan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/employees (1).png"))); // NOI18N
        Karyawan.setText("Karyawan");
        Karyawan.setBorderPainted(false);
        Karyawan.setContentAreaFilled(false);
        Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaryawanActionPerformed(evt);
            }
        });

        Supplier.setBackground(new java.awt.Color(0, 204, 255));
        Supplier.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hotel-supplier (1).png"))); // NOI18N
        Supplier.setText("Supplier");
        Supplier.setBorderPainted(false);
        Supplier.setContentAreaFilled(false);
        Supplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        Konsumen.setBackground(new java.awt.Color(0, 204, 255));
        Konsumen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Konsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/people (1).png"))); // NOI18N
        Konsumen.setText("Konsumen");
        Konsumen.setBorderPainted(false);
        Konsumen.setContentAreaFilled(false);
        Konsumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Konsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonsumenActionPerformed(evt);
            }
        });

        Obat.setBackground(new java.awt.Color(0, 204, 255));
        Obat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/tablet-and-pill (1).png"))); // NOI18N
        Obat.setText("Obat");
        Obat.setBorderPainted(false);
        Obat.setContentAreaFilled(false);
        Obat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        ResepDokter.setBackground(new java.awt.Color(0, 204, 255));
        ResepDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ResepDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/approve-invoice (1).png"))); // NOI18N
        ResepDokter.setText("Resep Dokter");
        ResepDokter.setBorderPainted(false);
        ResepDokter.setContentAreaFilled(false);
        ResepDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ResepDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResepDokterActionPerformed(evt);
            }
        });

        FakturPenjualan.setBackground(new java.awt.Color(0, 204, 255));
        FakturPenjualan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FakturPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/invoice.png"))); // NOI18N
        FakturPenjualan.setText("Faktur Penjualan");
        FakturPenjualan.setBorderPainted(false);
        FakturPenjualan.setContentAreaFilled(false);
        FakturPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FakturPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakturPenjualanActionPerformed(evt);
            }
        });

        Cabang.setBackground(new java.awt.Color(0, 204, 255));
        Cabang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cabang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/pharmacy (1).png"))); // NOI18N
        Cabang.setText("Cabang");
        Cabang.setBorderPainted(false);
        Cabang.setContentAreaFilled(false);
        Cabang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CabangActionPerformed(evt);
            }
        });

        Gaji.setBackground(new java.awt.Color(0, 204, 255));
        Gaji.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/money (1).png"))); // NOI18N
        Gaji.setText("Gaji");
        Gaji.setBorderPainted(false);
        Gaji.setContentAreaFilled(false);
        Gaji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GajiActionPerformed(evt);
            }
        });

        Jabatan.setBackground(new java.awt.Color(0, 204, 255));
        Jabatan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Jabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/manager (1).png"))); // NOI18N
        Jabatan.setText("Jabatan");
        Jabatan.setBorderPainted(false);
        Jabatan.setContentAreaFilled(false);
        Jabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabatanActionPerformed(evt);
            }
        });

        Tanggungan.setBackground(new java.awt.Color(0, 204, 255));
        Tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Tanggungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/users (1).png"))); // NOI18N
        Tanggungan.setText("Tanggungan");
        Tanggungan.setBorderPainted(false);
        Tanggungan.setContentAreaFilled(false);
        Tanggungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggunganActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/medicine (1).png"))); // NOI18N
        jLabel3.setText("Pharmacy");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Konsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ResepDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FakturPenjualan)
                                .addComponent(Cabang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home)
                .addGap(18, 18, 18)
                .addComponent(Karyawan)
                .addGap(18, 18, 18)
                .addComponent(Supplier)
                .addGap(18, 18, 18)
                .addComponent(Konsumen)
                .addGap(18, 18, 18)
                .addComponent(Obat)
                .addGap(18, 18, 18)
                .addComponent(ResepDokter)
                .addGap(18, 18, 18)
                .addComponent(FakturPenjualan)
                .addGap(18, 18, 18)
                .addComponent(Cabang)
                .addGap(18, 18, 18)
                .addComponent(Gaji)
                .addGap(18, 18, 18)
                .addComponent(Jabatan)
                .addGap(18, 18, 18)
                .addComponent(Tanggungan)
                .addGap(88, 88, 88))
        );

        no_cabang.setBackground(new java.awt.Color(36, 47, 65));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ID Karyawan");

        nama_cabang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_cabang.setForeground(new java.awt.Color(204, 204, 204));
        nama_cabang.setText("Jabatan");

        txt1.setBackground(new java.awt.Color(36, 47, 65));
        txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(204, 204, 204));
        txt1.setText("Enter ID Karyawan");
        txt1.setBorder(null);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(36, 47, 65));
        txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(204, 204, 204));
        txt2.setText("Enter Jabatan");
        txt2.setBorder(null);
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Input Data Jabatan");

        reset_jabatan.setBackground(new java.awt.Color(97, 212, 195));
        reset_jabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset_jabatan.setText("Reset");
        reset_jabatan.setBorder(null);
        reset_jabatan.setBorderPainted(false);
        reset_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jabatanActionPerformed(evt);
            }
        });

        input_jabatan.setBackground(new java.awt.Color(97, 212, 195));
        input_jabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        input_jabatan.setText("Input");
        input_jabatan.setBorder(null);
        input_jabatan.setBorderPainted(false);
        input_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_jabatanActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout no_cabangLayout = new javax.swing.GroupLayout(no_cabang);
        no_cabang.setLayout(no_cabangLayout);
        no_cabangLayout.setHorizontalGroup(
            no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_cabangLayout.createSequentialGroup()
                .addGroup(no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(no_cabangLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(no_cabangLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no_cabangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_cabang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no_cabangLayout.createSequentialGroup()
                        .addComponent(input_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );
        no_cabangLayout.setVerticalGroup(
            no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_cabangLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_cabang)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(no_cabangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        no_cabang1.setBackground(new java.awt.Color(36, 47, 65));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("ID Karyawan");

        nama_cabang1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama_cabang1.setForeground(new java.awt.Color(204, 204, 204));
        nama_cabang1.setText("Jabatan");

        txt3.setBackground(new java.awt.Color(36, 47, 65));
        txt3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(204, 204, 204));
        txt3.setText("Enter ID Karyawan");
        txt3.setBorder(null);
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });

        txt4.setBackground(new java.awt.Color(36, 47, 65));
        txt4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt4.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Data Jabatan");

        search_jabatan.setBackground(new java.awt.Color(97, 212, 195));
        search_jabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search_jabatan.setText("Search");
        search_jabatan.setBorder(null);
        search_jabatan.setBorderPainted(false);
        search_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jabatanActionPerformed(evt);
            }
        });

        update_jabatan.setBackground(new java.awt.Color(97, 212, 195));
        update_jabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update_jabatan.setText("Update");
        update_jabatan.setBorder(null);
        update_jabatan.setBorderPainted(false);
        update_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_jabatanActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        delete_jabatan.setBackground(new java.awt.Color(97, 212, 195));
        delete_jabatan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delete_jabatan.setText("Delete");
        delete_jabatan.setBorder(null);
        delete_jabatan.setBorderPainted(false);
        delete_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_jabatanActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout no_cabang1Layout = new javax.swing.GroupLayout(no_cabang1);
        no_cabang1.setLayout(no_cabang1Layout);
        no_cabang1Layout.setHorizontalGroup(
            no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no_cabang1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(146, 146, 146))
            .addGroup(no_cabang1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(no_cabang1Layout.createSequentialGroup()
                        .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(no_cabang1Layout.createSequentialGroup()
                                .addComponent(nama_cabang1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(no_cabang1Layout.createSequentialGroup()
                                        .addComponent(update_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(delete_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator8))
                                .addGap(98, 98, 98))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, no_cabang1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator9)
                            .addComponent(txt3))
                        .addGap(18, 18, 18)
                        .addComponent(search_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        no_cabang1Layout.setVerticalGroup(
            no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(no_cabang1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_cabang1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(no_cabang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        tabel_jabatan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabel_jabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Karyawan", "Jabatan"
            }
        ));
        tabel_jabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_jabatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_jabatan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(no_cabang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(no_cabang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_cabang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(no_cabang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home hh = new Home();
        try {
            this.dispose();
            hh.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanActionPerformed
        // TODO add your handling code here:
        Karyawan_data kd= new Karyawan_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KaryawanActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        // TODO add your handling code here:
        Supplier_data sd = new Supplier_data();
        try {
            this.dispose();
            sd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SupplierActionPerformed

    private void KonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonsumenActionPerformed
        // TODO add your handling code here:
        Konsumen_data kd = new Konsumen_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KonsumenActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
        // TODO add your handling code here:
        Obat_data od = new Obat_data();
        try {
            this.dispose();
            od.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ObatActionPerformed

    private void ResepDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResepDokterActionPerformed
        // TODO add your handling code here:
        ResepDokter_data rd = new ResepDokter_data();
        try {
            this.dispose();
            rd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ResepDokterActionPerformed

    private void FakturPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakturPenjualanActionPerformed
        // TODO add your handling code here:
        FakturPenjualan_data fd = new FakturPenjualan_data();
        try {
            this.dispose();
            fd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_FakturPenjualanActionPerformed

    private void CabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CabangActionPerformed
        // TODO add your handling code here:
        Cabang_data cd = new Cabang_data();
        try {
            this.dispose();
            cd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CabangActionPerformed

    private void GajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GajiActionPerformed
        // TODO add your handling code here:
        Gaji_data gd = new Gaji_data();
        try {
            this.dispose();
            gd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GajiActionPerformed

    private void JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabatanActionPerformed
        // TODO add your handling code here:
        Jabatan_data jd = new Jabatan_data();
        try {
            this.dispose();
            jd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JabatanActionPerformed

    private void TanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggunganActionPerformed
        // TODO add your handling code here:
        Tanggungan_data td = new Tanggungan_data();
        try {
            this.dispose();
            td.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_TanggunganActionPerformed

    private void reset_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jabatanActionPerformed
        // TODO add your handling code here:
        txt1.setText(null);
        txt2.setText(null);
    }//GEN-LAST:event_reset_jabatanActionPerformed

    private void input_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_jabatanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            String sql = " insert into jabatan(id_krw,jabatan) values(?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txt1.getText());
            pst.setString(2, txt2.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            DefaultTableModel model = (DefaultTableModel)tabel_jabatan.getModel();
            model.setRowCount(0);
            show_jabatan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertion Failed");
        }
    }//GEN-LAST:event_input_jabatanActionPerformed

    private void search_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jabatanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(" SELECT * FROM jabatan WHERE id_krw = '"+ txt3.getText()+"'");
            if (rs.next()){
                String i = txt3.getText();
                String a = rs.getString("jabatan");
                txt4.setText(a);                
                txt3.getText();
            } else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Invalid ID Karyawan");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_search_jabatanActionPerformed

    private void update_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_jabatanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("update jabatan set jabatan = '"+txt4.getText()+
                "' WHERE id_krw = '"+txt3.getText()+"'");
            if(rs.next()){
                String i = txt3.getText();
                String a = rs.getString("jabatan");
                txt4.setText(a);
                txt3.getText();
            }
            DefaultTableModel model = (DefaultTableModel)tabel_jabatan.getModel();
            model.setRowCount(0);
            show_jabatan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Updated");
        }
    }//GEN-LAST:event_update_jabatanActionPerformed

    private void delete_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_jabatanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("delete jabatan WHERE id_krw = '"+ txt3.getText()+"'");
            txt3.setText(null);
            txt4.setText(null);
            DefaultTableModel model = (DefaultTableModel)tabel_jabatan.getModel();
            model.setRowCount(0);
            show_jabatan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Deleted");
        }
    }//GEN-LAST:event_delete_jabatanActionPerformed

    private void tabel_jabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_jabatanMouseClicked
        // TODO add your handling code here:
        int i = tabel_jabatan.getSelectedRow();
        TableModel model = tabel_jabatan.getModel();
        txt3.setText(model.getValueAt(i,0).toString());
        txt4.setText(model.getValueAt(i,1).toString());  
    }//GEN-LAST:event_tabel_jabatanMouseClicked

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        // TODO add your handling code here:
        txt1.setText("");
    }//GEN-LAST:event_txt1MouseClicked

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        // TODO add your handling code here:
        txt2.setText("");
    }//GEN-LAST:event_txt2MouseClicked

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        // TODO add your handling code here:
        txt3.setText("");
    }//GEN-LAST:event_txt3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jabatan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jabatan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jabatan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jabatan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jabatan_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cabang;
    private javax.swing.JButton FakturPenjualan;
    private javax.swing.JButton Gaji;
    private javax.swing.JButton Home;
    private javax.swing.JButton Jabatan;
    private javax.swing.JButton Karyawan;
    private javax.swing.JButton Konsumen;
    private javax.swing.JButton Obat;
    private javax.swing.JButton ResepDokter;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton Tanggungan;
    private javax.swing.JButton delete_jabatan;
    private javax.swing.JButton input_jabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nama_cabang;
    private javax.swing.JLabel nama_cabang1;
    private javax.swing.JPanel no_cabang;
    private javax.swing.JPanel no_cabang1;
    private javax.swing.JButton reset_jabatan;
    private javax.swing.JButton search_jabatan;
    private javax.swing.JTable tabel_jabatan;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JButton update_jabatan;
    // End of variables declaration//GEN-END:variables
}
