/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup_form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DBSS075
 */
public class Karyawan_data extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan_data
     */
    Connection con= null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Karyawan_data() {
        initComponents();
        show_karyawan();
    }
    public ArrayList<karyawan> karyawans(){
        ArrayList<karyawan> karyawans = new ArrayList<>();
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url); 
            String queryl = " SELECT * FROM karyawan";
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(queryl);
            karyawan kr;
            while(rs.next()){
                kr = new karyawan(rs.getString("id_karyawan"), rs.getString("nama_karyawan")
                        , rs.getString("JK"), rs.getString("alamat_karyawan") , rs.getDate("tanggal_lahir"),
                        rs.getString("kota_lahir"), rs.getString("no_tlp_karyawan"),rs.getInt("no_cabang"));
                karyawans.add(kr);
            }
         }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         return karyawans;
    } 
    public  void show_karyawan(){
        ArrayList<karyawan> karyawans_list = karyawans();
        DefaultTableModel model = (DefaultTableModel )tabel_karyawan.getModel(); 
        Object[] row = new Object[8];
        for (int i = 0; i < karyawans_list.size(); i++) {
            row[0]= karyawans_list.get(i).getId_karyawan();
            row[1]= karyawans_list.get(i).getNama_karyawan();
            row[2]= karyawans_list.get(i).getJK();
            row[3]= karyawans_list.get(i).getAlamat_karyawan();
            row[4]= karyawans_list.get(i).getTanggal_lahir();
            row[5]= karyawans_list.get(i).getKota_lahir();
            row[6]= karyawans_list.get(i).getNo_tlp_karyawan();
            row[7]= karyawans_list.get(i).getNo_cabang();
            model.addRow(row);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id_karyawan = new javax.swing.JLabel();
        nama_karyawan = new javax.swing.JLabel();
        alamat_karyawan = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        reset_karyawan = new javax.swing.JButton();
        input_karyawan = new javax.swing.JButton();
        jenis_kelamin = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        no_tlp_karyawan = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        no_tlp_karyawan1 = new javax.swing.JLabel();
        no_tlp_karyawan2 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Karyawan = new javax.swing.JButton();
        Supplier = new javax.swing.JButton();
        Konsumen = new javax.swing.JButton();
        Obat = new javax.swing.JButton();
        ResepDokter = new javax.swing.JButton();
        FakturPenjualan = new javax.swing.JButton();
        Cabang = new javax.swing.JButton();
        Gaji = new javax.swing.JButton();
        Jabatan = new javax.swing.JButton();
        Tanggungan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_karyawan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        id_karyawan2 = new javax.swing.JLabel();
        nama_karyawan1 = new javax.swing.JLabel();
        alamat_karyawan1 = new javax.swing.JLabel();
        ttl1 = new javax.swing.JLabel();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        search_karyawan = new javax.swing.JButton();
        update_karyawan = new javax.swing.JButton();
        jenis_kelamin1 = new javax.swing.JLabel();
        txt13 = new javax.swing.JTextField();
        no_tlp_karyawan3 = new javax.swing.JLabel();
        txt14 = new javax.swing.JTextField();
        no_tlp_karyawan4 = new javax.swing.JLabel();
        no_tlp_karyawan5 = new javax.swing.JLabel();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        delete_karyawan = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        id_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        id_karyawan.setForeground(new java.awt.Color(204, 204, 204));
        id_karyawan.setText("ID Karyawan");

        nama_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nama_karyawan.setForeground(new java.awt.Color(204, 204, 204));
        nama_karyawan.setText("Nama Karyawan");

        alamat_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        alamat_karyawan.setForeground(new java.awt.Color(204, 204, 204));
        alamat_karyawan.setText("Jenis Kelamin");
        alamat_karyawan.setToolTipText("");

        ttl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ttl.setForeground(new java.awt.Color(204, 204, 204));
        ttl.setText("Alamat Karyawan");

        txt1.setBackground(new java.awt.Color(36, 47, 65));
        txt1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(204, 204, 204));
        txt1.setText("Enter ID Karyawan");
        txt1.setBorder(null);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(36, 47, 65));
        txt2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt2.setForeground(new java.awt.Color(204, 204, 204));
        txt2.setText("Enter Nama Karyawan");
        txt2.setBorder(null);
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });

        txt3.setBackground(new java.awt.Color(36, 47, 65));
        txt3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt3.setForeground(new java.awt.Color(204, 204, 204));
        txt3.setText("Enter Jenis Kelamin");
        txt3.setBorder(null);
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });

        txt4.setEditable(false);
        txt4.setBackground(new java.awt.Color(36, 47, 65));
        txt4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt4.setForeground(new java.awt.Color(204, 204, 204));
        txt4.setText("Enter Alamat Karyawan");
        txt4.setBorder(null);
        txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Input Data Karyawan");

        reset_karyawan.setBackground(new java.awt.Color(97, 212, 195));
        reset_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset_karyawan.setText("Reset");
        reset_karyawan.setBorder(null);
        reset_karyawan.setBorderPainted(false);
        reset_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_karyawanActionPerformed(evt);
            }
        });

        input_karyawan.setBackground(new java.awt.Color(97, 212, 195));
        input_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        input_karyawan.setText("Input");
        input_karyawan.setBorder(null);
        input_karyawan.setBorderPainted(false);
        input_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_karyawanActionPerformed(evt);
            }
        });

        jenis_kelamin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jenis_kelamin.setForeground(new java.awt.Color(204, 204, 204));
        jenis_kelamin.setText("Tanggal Lahir");

        txt5.setBackground(new java.awt.Color(36, 47, 65));
        txt5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt5.setForeground(new java.awt.Color(204, 204, 204));
        txt5.setText("Enter Tanggal Lahir");
        txt5.setBorder(null);
        txt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt5MouseClicked(evt);
            }
        });

        no_tlp_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_tlp_karyawan.setForeground(new java.awt.Color(204, 204, 204));
        no_tlp_karyawan.setText("Kota Lahir");

        txt6.setBackground(new java.awt.Color(36, 47, 65));
        txt6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt6.setForeground(new java.awt.Color(204, 204, 204));
        txt6.setText("Enter Kota Lahir");
        txt6.setBorder(null);
        txt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt6MouseClicked(evt);
            }
        });

        no_tlp_karyawan1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_tlp_karyawan1.setForeground(new java.awt.Color(204, 204, 204));
        no_tlp_karyawan1.setText("No Tlp Karyawan");

        no_tlp_karyawan2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_tlp_karyawan2.setForeground(new java.awt.Color(204, 204, 204));
        no_tlp_karyawan2.setText("No Cabang");

        txt7.setBackground(new java.awt.Color(36, 47, 65));
        txt7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt7.setForeground(new java.awt.Color(204, 204, 204));
        txt7.setText("Enter No Tlp Karyawan");
        txt7.setBorder(null);
        txt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt7MouseClicked(evt);
            }
        });

        txt8.setBackground(new java.awt.Color(36, 47, 65));
        txt8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt8.setForeground(new java.awt.Color(204, 204, 204));
        txt8.setText("Enter No Cabang");
        txt8.setBorder(null);
        txt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt8MouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(no_tlp_karyawan2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(input_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reset_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamat_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_tlp_karyawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_tlp_karyawan1))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txt6, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txt7, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(jSeparator6)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator8)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator10)
                                    .addComponent(jSeparator11)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_karyawan))
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat_karyawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttl)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis_kelamin)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_tlp_karyawan)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_tlp_karyawan1))
                .addGap(3, 3, 3)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_tlp_karyawan2))
                .addGap(3, 3, 3)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        Home.setBackground(new java.awt.Color(0, 204, 255));
        Home.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/avatar (1).png"))); // NOI18N
        Home.setText(" Admin Profile");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Karyawan.setBackground(new java.awt.Color(0, 204, 255));
        Karyawan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/employees (1).png"))); // NOI18N
        Karyawan.setText("Karyawan");
        Karyawan.setBorderPainted(false);
        Karyawan.setContentAreaFilled(false);
        Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaryawanActionPerformed(evt);
            }
        });

        Supplier.setBackground(new java.awt.Color(0, 204, 255));
        Supplier.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hotel-supplier (1).png"))); // NOI18N
        Supplier.setText("Supplier");
        Supplier.setBorderPainted(false);
        Supplier.setContentAreaFilled(false);
        Supplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        Konsumen.setBackground(new java.awt.Color(0, 204, 255));
        Konsumen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Konsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/people (1).png"))); // NOI18N
        Konsumen.setText("Konsumen");
        Konsumen.setBorderPainted(false);
        Konsumen.setContentAreaFilled(false);
        Konsumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Konsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonsumenActionPerformed(evt);
            }
        });

        Obat.setBackground(new java.awt.Color(0, 204, 255));
        Obat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/tablet-and-pill (1).png"))); // NOI18N
        Obat.setText("Obat");
        Obat.setBorderPainted(false);
        Obat.setContentAreaFilled(false);
        Obat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        ResepDokter.setBackground(new java.awt.Color(0, 204, 255));
        ResepDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ResepDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/approve-invoice (1).png"))); // NOI18N
        ResepDokter.setText("Resep Dokter");
        ResepDokter.setBorderPainted(false);
        ResepDokter.setContentAreaFilled(false);
        ResepDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ResepDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResepDokterActionPerformed(evt);
            }
        });

        FakturPenjualan.setBackground(new java.awt.Color(0, 204, 255));
        FakturPenjualan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FakturPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/invoice.png"))); // NOI18N
        FakturPenjualan.setText("Faktur Penjualan");
        FakturPenjualan.setBorderPainted(false);
        FakturPenjualan.setContentAreaFilled(false);
        FakturPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FakturPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakturPenjualanActionPerformed(evt);
            }
        });

        Cabang.setBackground(new java.awt.Color(0, 204, 255));
        Cabang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cabang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/pharmacy (1).png"))); // NOI18N
        Cabang.setText("Cabang");
        Cabang.setBorderPainted(false);
        Cabang.setContentAreaFilled(false);
        Cabang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CabangActionPerformed(evt);
            }
        });

        Gaji.setBackground(new java.awt.Color(0, 204, 255));
        Gaji.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/money (1).png"))); // NOI18N
        Gaji.setText("Gaji");
        Gaji.setBorderPainted(false);
        Gaji.setContentAreaFilled(false);
        Gaji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GajiActionPerformed(evt);
            }
        });

        Jabatan.setBackground(new java.awt.Color(0, 204, 255));
        Jabatan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Jabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/manager (1).png"))); // NOI18N
        Jabatan.setText("Jabatan");
        Jabatan.setBorderPainted(false);
        Jabatan.setContentAreaFilled(false);
        Jabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabatanActionPerformed(evt);
            }
        });

        Tanggungan.setBackground(new java.awt.Color(0, 204, 255));
        Tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Tanggungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/users (1).png"))); // NOI18N
        Tanggungan.setText("Tanggungan");
        Tanggungan.setBorderPainted(false);
        Tanggungan.setContentAreaFilled(false);
        Tanggungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggunganActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/medicine (1).png"))); // NOI18N
        jLabel2.setText("Pharmacy");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Konsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResepDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FakturPenjualan)
                            .addComponent(Cabang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home)
                .addGap(18, 18, 18)
                .addComponent(Karyawan)
                .addGap(18, 18, 18)
                .addComponent(Supplier)
                .addGap(18, 18, 18)
                .addComponent(Konsumen)
                .addGap(18, 18, 18)
                .addComponent(Obat)
                .addGap(18, 18, 18)
                .addComponent(ResepDokter)
                .addGap(18, 18, 18)
                .addComponent(FakturPenjualan)
                .addGap(18, 18, 18)
                .addComponent(Cabang)
                .addGap(18, 18, 18)
                .addComponent(Gaji)
                .addGap(18, 18, 18)
                .addComponent(Jabatan)
                .addGap(18, 18, 18)
                .addComponent(Tanggungan)
                .addGap(113, 113, 113))
        );

        tabel_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabel_karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Karyawan", "Nama ", "Jenis Kelamin", "Alamat ", "Tanggal Lahir", "Kota Lahir", "No Tlp ", "No Cabang"
            }
        ));
        tabel_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_karyawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_karyawan);

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        id_karyawan2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        id_karyawan2.setForeground(new java.awt.Color(204, 204, 204));
        id_karyawan2.setText("ID Karyawan");

        nama_karyawan1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nama_karyawan1.setForeground(new java.awt.Color(204, 204, 204));
        nama_karyawan1.setText("Nama Karyawan");

        alamat_karyawan1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        alamat_karyawan1.setForeground(new java.awt.Color(204, 204, 204));
        alamat_karyawan1.setText("Jenis Kelamin");

        ttl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ttl1.setForeground(new java.awt.Color(204, 204, 204));
        ttl1.setText("Alamat Karyawan");

        txt9.setBackground(new java.awt.Color(36, 47, 65));
        txt9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt9.setForeground(new java.awt.Color(204, 204, 204));
        txt9.setText("Enter ID Karyawan");
        txt9.setBorder(null);
        txt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt9MouseClicked(evt);
            }
        });
        txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9ActionPerformed(evt);
            }
        });

        txt10.setBackground(new java.awt.Color(36, 47, 65));
        txt10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt10.setForeground(new java.awt.Color(204, 204, 204));
        txt10.setBorder(null);

        txt11.setBackground(new java.awt.Color(36, 47, 65));
        txt11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt11.setForeground(new java.awt.Color(204, 204, 204));
        txt11.setBorder(null);

        txt12.setBackground(new java.awt.Color(36, 47, 65));
        txt12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt12.setForeground(new java.awt.Color(204, 204, 204));
        txt12.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Data Karyawan");

        search_karyawan.setBackground(new java.awt.Color(97, 212, 195));
        search_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search_karyawan.setText("Search");
        search_karyawan.setBorder(null);
        search_karyawan.setBorderPainted(false);
        search_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_karyawanActionPerformed(evt);
            }
        });

        update_karyawan.setBackground(new java.awt.Color(97, 212, 195));
        update_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update_karyawan.setText("Update");
        update_karyawan.setBorder(null);
        update_karyawan.setBorderPainted(false);
        update_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_karyawanActionPerformed(evt);
            }
        });

        jenis_kelamin1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jenis_kelamin1.setForeground(new java.awt.Color(204, 204, 204));
        jenis_kelamin1.setText("Tanggal Lahir");

        txt13.setBackground(new java.awt.Color(36, 47, 65));
        txt13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt13.setForeground(new java.awt.Color(204, 204, 204));
        txt13.setBorder(null);

        no_tlp_karyawan3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_tlp_karyawan3.setForeground(new java.awt.Color(204, 204, 204));
        no_tlp_karyawan3.setText("Kota Lahir");

        txt14.setBackground(new java.awt.Color(36, 47, 65));
        txt14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt14.setForeground(new java.awt.Color(204, 204, 204));
        txt14.setBorder(null);

        no_tlp_karyawan4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_tlp_karyawan4.setForeground(new java.awt.Color(204, 204, 204));
        no_tlp_karyawan4.setText("No Tlp Karyawan");

        no_tlp_karyawan5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        no_tlp_karyawan5.setForeground(new java.awt.Color(204, 204, 204));
        no_tlp_karyawan5.setText("No Cabang");

        txt15.setBackground(new java.awt.Color(36, 47, 65));
        txt15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt15.setForeground(new java.awt.Color(204, 204, 204));
        txt15.setBorder(null);

        txt16.setBackground(new java.awt.Color(36, 47, 65));
        txt16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt16.setForeground(new java.awt.Color(204, 204, 204));
        txt16.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        delete_karyawan.setBackground(new java.awt.Color(97, 212, 195));
        delete_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delete_karyawan.setText("Delete");
        delete_karyawan.setBorder(null);
        delete_karyawan.setBorderPainted(false);
        delete_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_karyawanActionPerformed(evt);
            }
        });

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator17.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator18.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator20.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator20.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator21.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator21.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(119, 119, 119))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(id_karyawan2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator21)
                            .addComponent(txt9, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addComponent(search_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(alamat_karyawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(nama_karyawan1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis_kelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_tlp_karyawan3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_tlp_karyawan4)
                                    .addComponent(ttl1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(update_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(delete_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator15)
                                        .addComponent(jSeparator16)
                                        .addComponent(jSeparator17)
                                        .addComponent(jSeparator18)
                                        .addComponent(jSeparator19))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(no_tlp_karyawan5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator14))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karyawan2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_karyawan1)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat_karyawan1))
                .addGap(1, 1, 1)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttl1)
                    .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis_kelamin1)
                    .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_tlp_karyawan3)
                            .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_tlp_karyawan4)
                    .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(no_tlp_karyawan5)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_karyawanActionPerformed
        // TODO add your handling code here:
        txt1.setText(null);
        txt2.setText(null);
        txt3.setText(null);
        txt4.setText(null);
        txt5.setText(null);
        txt6.setText(null);
        txt7.setText(null);
        txt8.setText(null);
    }//GEN-LAST:event_reset_karyawanActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home hh = new Home();
        try {
            this.dispose();
            hh.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanActionPerformed
        // TODO add your handling code here:
         Karyawan_data kd= new Karyawan_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KaryawanActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        // TODO add your handling code here:
        Supplier_data sd = new Supplier_data();
        try {
            this.dispose();
            sd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SupplierActionPerformed

    private void KonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonsumenActionPerformed
        // TODO add your handling code here:
        Konsumen_data kd = new Konsumen_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KonsumenActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
        // TODO add your handling code here:
        Obat_data od = new Obat_data();
        try {
            this.dispose();
            od.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ObatActionPerformed

    private void ResepDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResepDokterActionPerformed
        // TODO add your handling code here:
        ResepDokter_data rd = new ResepDokter_data();
        try {
            this.dispose();
            rd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ResepDokterActionPerformed

    private void FakturPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakturPenjualanActionPerformed
        // TODO add your handling code here:
        FakturPenjualan_data fd = new FakturPenjualan_data();
        try {
            this.dispose();
            fd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_FakturPenjualanActionPerformed

    private void CabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CabangActionPerformed
        // TODO add your handling code here:
        Cabang_data cd = new Cabang_data();
        try {
            this.dispose();
            cd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CabangActionPerformed

    private void GajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GajiActionPerformed
        // TODO add your handling code here:
        Gaji_data gd = new Gaji_data();
        try {
            this.dispose();
            gd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GajiActionPerformed

    private void JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabatanActionPerformed
        // TODO add your handling code here:
        Jabatan_data jd = new Jabatan_data();
        try {
            this.dispose();
            jd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JabatanActionPerformed

    private void TanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggunganActionPerformed
        // TODO add your handling code here:
        Tanggungan_data td = new Tanggungan_data();
        try {
            this.dispose();
            td.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_TanggunganActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt9ActionPerformed

    private void search_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_karyawanActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(" SELECT * FROM karyawan WHERE id_karyawan = '"+ txt9.getText()+"'"); 
            if (rs.next()){
                String i = txt9.getText();
                String a = rs.getString("nama_karyawan");
                String b = rs.getString("JK");
                String c = rs.getString("alamat_karyawan");
                String d = rs.getString("tanggal_lahir");
                String f = rs.getString("kota_lahir");
                String g = rs.getString("no_tlp_karyawan");
                String h = rs.getString("no_cabang");
                txt10.setText(a);
                txt11.setText(b);
                txt12.setText(c);
                txt13.setText(d);
                txt14.setText(f);
                txt15.setText(g);
                txt16.setText(h);
                txt9.getText();
            } else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Invalid ID Karyawan");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_search_karyawanActionPerformed

    private void delete_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_karyawanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("delete karyawan WHERE id_karyawan = '"+ txt9.getText()+"'");
            txt10.setText(null);
                txt11.setText(null);
                txt12.setText(null);
                txt13.setText(null);
                txt14.setText(null);
                txt15.setText(null);
                txt16.setText(null);
            DefaultTableModel model = (DefaultTableModel)tabel_karyawan.getModel();
            model.setRowCount(0);
            show_karyawan();                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Deleted");
        }
    }//GEN-LAST:event_delete_karyawanActionPerformed

    private void input_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_karyawanActionPerformed
        // TODO add your handling code here:
        String a = txt1.getText();
        String b = txt2.getText();
        String c = txt3.getText();
        String d = txt4.getText();
        String f = txt5.getText();
        String g = txt6.getText();
        String h = txt7.getText();
        String i = txt8.getText();
       
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            String sql = " insert into karyawan(id_karyawan,nama_karyawan,JK,alamat_karyawan,tanggal_lahir,kota_lahir,no_tlp_karyawan,no_cabang) values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txt1.getText());
            pst.setString(2, txt2.getText());
            pst.setString(3, txt3.getText());
            pst.setString(4, txt4.getText());
            pst.setString(5, txt5.getText());
            pst.setString(6, txt6.getText());
            pst.setString(7, txt7.getText());
            pst.setString(8, txt8.getText());
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)tabel_karyawan.getModel();
            model.setRowCount(0);
            show_karyawan();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertion Failed");
        }
    }//GEN-LAST:event_input_karyawanActionPerformed

    private void update_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_karyawanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("update karyawan set nama_karyawan = '"+txt10.getText()+
                     "',JK = '"+txt11.getText()+
                     "',alamat_karyawan = '"+txt12.getText()+
                     "',tanggal_lahir = '"+txt13.getText()+
                     "',kota_lahir = '"+txt14.getText()+
                     "',no_tlp_karyawan = '"+txt15.getText()+
                     "',no_cabang = '"+txt16.getText()+
                     "' WHERE id_karyawan = '"+txt9.getText()+"'");             
             if(rs.next()){                
               String i = txt9.getText();
                String a = rs.getString("nama_karyawan");
                String b = rs.getString("JK");
                String c = rs.getString("alamat_karyawan");
                String d = rs.getString("tanggal_lahir");
                String f = rs.getString("kota_lahir");
                String g = rs.getString("no_tlp_karyawan");
                String h = rs.getString("no_cabang");
                txt10.setText(a);
                txt11.setText(b);
                txt12.setText(c);
                txt13.setText(d);
                txt14.setText(f);
                txt15.setText(g);
                txt16.setText(h);
                txt9.getText();           
             }            
             DefaultTableModel model = (DefaultTableModel)tabel_karyawan.getModel(); 
             model.setRowCount(0);
             show_karyawan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Updated"); 
        }
    }//GEN-LAST:event_update_karyawanActionPerformed

    private void tabel_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_karyawanMouseClicked
        // TODO add your handling code here:
        int i = tabel_karyawan.getSelectedRow();
        TableModel model = tabel_karyawan.getModel();
        txt9.setText(model.getValueAt(i,0).toString());
        txt10.setText(model.getValueAt(i,1).toString());
        txt11.setText(model.getValueAt(i,2).toString());
        txt12.setText(model.getValueAt(i,3).toString());
        txt13.setText(model.getValueAt(i,4).toString());
        txt14.setText(model.getValueAt(i,5).toString());
        txt15.setText(model.getValueAt(i,6).toString());
        txt16.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_tabel_karyawanMouseClicked

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        // TODO add your handling code here:
        txt1.setText("");
    }//GEN-LAST:event_txt1MouseClicked

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        // TODO add your handling code here:
        txt2.setText("");
    }//GEN-LAST:event_txt2MouseClicked

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        // TODO add your handling code here:
        txt3.setText("");
    }//GEN-LAST:event_txt3MouseClicked

    private void txt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MouseClicked
        // TODO add your handling code here:
        txt4.setText("");
    }//GEN-LAST:event_txt4MouseClicked

    private void txt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt5MouseClicked
        // TODO add your handling code here:
        txt5.setText("");
    }//GEN-LAST:event_txt5MouseClicked

    private void txt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt6MouseClicked
        // TODO add your handling code here:
        txt6.setText("");
    }//GEN-LAST:event_txt6MouseClicked

    private void txt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt7MouseClicked
        // TODO add your handling code here:
        txt7.setText("");
    }//GEN-LAST:event_txt7MouseClicked

    private void txt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt8MouseClicked
        // TODO add your handling code here:
        txt8.setText("");
    }//GEN-LAST:event_txt8MouseClicked

    private void txt9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt9MouseClicked
        // TODO add your handling code here:
        txt9.setText("");
    }//GEN-LAST:event_txt9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cabang;
    private javax.swing.JButton FakturPenjualan;
    private javax.swing.JButton Gaji;
    private javax.swing.JButton Home;
    private javax.swing.JButton Jabatan;
    private javax.swing.JButton Karyawan;
    private javax.swing.JButton Konsumen;
    private javax.swing.JButton Obat;
    private javax.swing.JButton ResepDokter;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton Tanggungan;
    private javax.swing.JLabel alamat_karyawan;
    private javax.swing.JLabel alamat_karyawan1;
    private javax.swing.JButton delete_karyawan;
    private javax.swing.JLabel id_karyawan;
    private javax.swing.JLabel id_karyawan2;
    private javax.swing.JButton input_karyawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jenis_kelamin;
    private javax.swing.JLabel jenis_kelamin1;
    private javax.swing.JLabel nama_karyawan;
    private javax.swing.JLabel nama_karyawan1;
    private javax.swing.JLabel no_tlp_karyawan;
    private javax.swing.JLabel no_tlp_karyawan1;
    private javax.swing.JLabel no_tlp_karyawan2;
    private javax.swing.JLabel no_tlp_karyawan3;
    private javax.swing.JLabel no_tlp_karyawan4;
    private javax.swing.JLabel no_tlp_karyawan5;
    private javax.swing.JButton reset_karyawan;
    private javax.swing.JButton search_karyawan;
    private javax.swing.JTable tabel_karyawan;
    private javax.swing.JLabel ttl;
    private javax.swing.JLabel ttl1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JButton update_karyawan;
    // End of variables declaration//GEN-END:variables
}
