/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup_form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DBSS075
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    Connection con= null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        member_firstname = new javax.swing.JTextField();
        member_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        signup = new javax.swing.JPanel();
        signup_member = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        member_lastname = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        member_username = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        signin_member = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\DBSS075\\Downloads\\sign (2).png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 72)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" E-Pharmacy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        member_firstname.setBackground(new java.awt.Color(36, 47, 65));
        member_firstname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        member_firstname.setForeground(new java.awt.Color(255, 255, 255));
        member_firstname.setText("Enter First Name");
        member_firstname.setBorder(null);
        member_firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                member_firstnameFocusGained(evt);
            }
        });
        member_firstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_firstnameMouseClicked(evt);
            }
        });
        member_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(member_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 350, -1));

        member_password.setBackground(new java.awt.Color(36, 47, 65));
        member_password.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        member_password.setForeground(new java.awt.Color(255, 255, 255));
        member_password.setText("***********");
        member_password.setBorder(null);
        member_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                member_passwordFocusGained(evt);
            }
        });
        member_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_passwordMouseClicked(evt);
            }
        });
        member_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(member_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 350, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 350, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 350, 10));

        signup.setBackground(new java.awt.Color(97, 212, 195));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        signup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup_member.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        signup_member.setForeground(new java.awt.Color(51, 51, 51));
        signup_member.setText("Sign Up");
        signup_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_memberMouseClicked(evt);
            }
        });
        signup.add(signup_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 100, 50));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 120, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("MEMBER SIGN UP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        member_lastname.setBackground(new java.awt.Color(36, 47, 65));
        member_lastname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        member_lastname.setForeground(new java.awt.Color(255, 255, 255));
        member_lastname.setText("Enter Last Name");
        member_lastname.setBorder(null);
        member_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                member_lastnameFocusGained(evt);
            }
        });
        member_lastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_lastnameMouseClicked(evt);
            }
        });
        member_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(member_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 350, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 350, 10));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        member_username.setBackground(new java.awt.Color(36, 47, 65));
        member_username.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        member_username.setForeground(new java.awt.Color(255, 255, 255));
        member_username.setText("Enter Username");
        member_username.setBorder(null);
        member_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                member_usernameFocusGained(evt);
            }
        });
        member_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_usernameMouseClicked(evt);
            }
        });
        member_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(member_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 350, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 350, 10));

        signin_member.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        signin_member.setForeground(new java.awt.Color(204, 204, 204));
        signin_member.setText("Already A Member? Sign IN");
        signin_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signin_memberMouseClicked(evt);
            }
        });
        jPanel1.add(signin_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void member_firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_firstnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_member_firstnameFocusGained

    private void member_firstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_firstnameMouseClicked
        // TODO add your handling code here:
        member_firstname.setText("");
    }//GEN-LAST:event_member_firstnameMouseClicked

    private void member_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_firstnameActionPerformed

    private void member_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_passwordFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_member_passwordFocusGained

    private void member_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_passwordMouseClicked
        // TODO add your handling code here:
        member_password.setText("");
    }//GEN-LAST:event_member_passwordMouseClicked

    private void member_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_passwordActionPerformed

    private void signup_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_memberMouseClicked
        // TODO add your handling code here:
//        String a = member_firstname.getText();
//        String b = member_lastname.getText();
//        String c = member_username.getText();
//        String d = new String(member_password.getPassword());
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            String sql = "insert into login_user(User_First_Name,User_Last_Name,User_User_Name,User_User_Password) values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, member_firstname.getText());
            pst.setString(2, member_lastname.getText());
            pst.setString(3, member_username.getText());
            pst.setString(4, new String(member_password.getPassword()));
            pst.execute();
            JOptionPane.showMessageDialog(null, "Sign Up Succesfully");
            this.dispose(); 
            Login ll = new Login();
            ll.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sign Up Failed");
            System.out.println(e);
        }
    }//GEN-LAST:event_signup_memberMouseClicked

    private void member_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_lastnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_member_lastnameFocusGained

    private void member_lastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_lastnameMouseClicked
        // TODO add your handling code here:
        member_lastname.setText("");
    }//GEN-LAST:event_member_lastnameMouseClicked

    private void member_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_lastnameActionPerformed

    private void member_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_member_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_member_usernameFocusGained

    private void member_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_usernameMouseClicked
        // TODO add your handling code here:
        member_username.setText("");
    }//GEN-LAST:event_member_usernameMouseClicked

    private void member_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_usernameActionPerformed

    private void signin_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signin_memberMouseClicked
        // TODO add your handling code here:Signup ss = new Signup();
        Login ll = new Login();
        try {
            this.dispose();
            ll.show();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_signin_memberMouseClicked

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField member_firstname;
    private javax.swing.JTextField member_lastname;
    private javax.swing.JPasswordField member_password;
    private javax.swing.JTextField member_username;
    private javax.swing.JLabel signin_member;
    private javax.swing.JPanel signup;
    private javax.swing.JLabel signup_member;
    // End of variables declaration//GEN-END:variables
}
