/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signup_form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DBSS075
 */
public class Tanggungan_data extends javax.swing.JFrame {

    /**
     * Creates new form Tanggungan_data
     */
    Connection con= null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Tanggungan_data() {
        initComponents();
        show_tanggungan();
    }
    public ArrayList<Tanggungan> tanggungan(){
        ArrayList<Tanggungan> tanggungans = new ArrayList<>();
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url); 
            String queryl = " SELECT * FROM tanggungan";
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(queryl);
            Tanggungan tanggungan;
            while(rs.next()){
                tanggungan = new Tanggungan(rs.getString("nama"), rs.getDate("ttl")
                        ,rs.getString("JK"), rs.getString("hubungan"),rs.getString("id_karyawan"));
                tanggungans.add(tanggungan);
            }
         }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         return tanggungans;
    } 
    public  void show_tanggungan(){
        ArrayList<Tanggungan> tanggungan_list = tanggungan();
        DefaultTableModel model = (DefaultTableModel )tabel_tanggungan.getModel(); 
        Object[] row = new Object[5];
        for (int i = 0; i < tanggungan_list.size(); i++) {
            row[0]= tanggungan_list.get(i).getNama();
            row[1]= tanggungan_list.get(i).getTtl();
            row[2]= tanggungan_list.get(i).getJK();
            row[3]= tanggungan_list.get(i).getHubungan();
            row[4]= tanggungan_list.get(i).getId_karyawan();             
            model.addRow(row);
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        ttl_tanggungan = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        reset_tanggungan = new javax.swing.JButton();
        input_tanggungan = new javax.swing.JButton();
        id_karyawan_tanggungan = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        Karyawan = new javax.swing.JButton();
        Supplier = new javax.swing.JButton();
        Konsumen = new javax.swing.JButton();
        Obat = new javax.swing.JButton();
        ResepDokter = new javax.swing.JButton();
        FakturPenjualan = new javax.swing.JButton();
        Cabang = new javax.swing.JButton();
        Gaji = new javax.swing.JButton();
        Jabatan = new javax.swing.JButton();
        Tanggungan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_tanggungan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nama1 = new javax.swing.JLabel();
        ttl_tanggungan1 = new javax.swing.JLabel();
        jk1 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        search_karyawan = new javax.swing.JButton();
        update_tanggungan = new javax.swing.JButton();
        id_karyawan_tanggungan1 = new javax.swing.JLabel();
        txt10 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        delete_tanggungan = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setForeground(new java.awt.Color(204, 204, 204));
        nama.setText("Nama");

        ttl_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl_tanggungan.setForeground(new java.awt.Color(204, 204, 204));
        ttl_tanggungan.setText("Tanggal Lahir");

        jk.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk.setForeground(new java.awt.Color(204, 204, 204));
        jk.setText("Jenis Kelamin");

        status.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        status.setForeground(new java.awt.Color(204, 204, 204));
        status.setText("Hubungan");

        txt1.setBackground(new java.awt.Color(36, 47, 65));
        txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(204, 204, 204));
        txt1.setText("Enter Nama");
        txt1.setBorder(null);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(36, 47, 65));
        txt2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(204, 204, 204));
        txt2.setText("Enter Tanggal Lahir");
        txt2.setBorder(null);
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });

        txt3.setBackground(new java.awt.Color(36, 47, 65));
        txt3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(204, 204, 204));
        txt3.setText("Enter Jenis Kelamin");
        txt3.setBorder(null);
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });

        txt4.setBackground(new java.awt.Color(36, 47, 65));
        txt4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt4.setForeground(new java.awt.Color(204, 204, 204));
        txt4.setText("Enter Hubungan");
        txt4.setBorder(null);
        txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Input Data Tanggungan");

        reset_tanggungan.setBackground(new java.awt.Color(97, 212, 195));
        reset_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reset_tanggungan.setText("Reset");
        reset_tanggungan.setBorder(null);
        reset_tanggungan.setBorderPainted(false);
        reset_tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_tanggunganActionPerformed(evt);
            }
        });

        input_tanggungan.setBackground(new java.awt.Color(97, 212, 195));
        input_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        input_tanggungan.setText("Input");
        input_tanggungan.setBorder(null);
        input_tanggungan.setBorderPainted(false);
        input_tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tanggunganActionPerformed(evt);
            }
        });

        id_karyawan_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_karyawan_tanggungan.setForeground(new java.awt.Color(204, 204, 204));
        id_karyawan_tanggungan.setText("ID Karyawan");

        txt5.setBackground(new java.awt.Color(36, 47, 65));
        txt5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt5.setForeground(new java.awt.Color(204, 204, 204));
        txt5.setText("Enter ID Karyawan");
        txt5.setBorder(null);
        txt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt5MouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_karyawan_tanggungan)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk)
                    .addComponent(ttl_tanggungan)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(input_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reset_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(98, 98, 98)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttl_tanggungan))
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk))
                .addGap(1, 1, 1)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status))
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karyawan_tanggungan))
                .addGap(2, 2, 2)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));

        Home.setBackground(new java.awt.Color(0, 204, 255));
        Home.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/avatar (1).png"))); // NOI18N
        Home.setText(" Admin Profile");
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Karyawan.setBackground(new java.awt.Color(0, 204, 255));
        Karyawan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/employees (1).png"))); // NOI18N
        Karyawan.setText("Karyawan");
        Karyawan.setBorderPainted(false);
        Karyawan.setContentAreaFilled(false);
        Karyawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaryawanActionPerformed(evt);
            }
        });

        Supplier.setBackground(new java.awt.Color(0, 204, 255));
        Supplier.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/hotel-supplier (1).png"))); // NOI18N
        Supplier.setText("Supplier");
        Supplier.setBorderPainted(false);
        Supplier.setContentAreaFilled(false);
        Supplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierActionPerformed(evt);
            }
        });

        Konsumen.setBackground(new java.awt.Color(0, 204, 255));
        Konsumen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Konsumen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/people (1).png"))); // NOI18N
        Konsumen.setText("Konsumen");
        Konsumen.setBorderPainted(false);
        Konsumen.setContentAreaFilled(false);
        Konsumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Konsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonsumenActionPerformed(evt);
            }
        });

        Obat.setBackground(new java.awt.Color(0, 204, 255));
        Obat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/tablet-and-pill (1).png"))); // NOI18N
        Obat.setText("Obat");
        Obat.setBorderPainted(false);
        Obat.setContentAreaFilled(false);
        Obat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        ResepDokter.setBackground(new java.awt.Color(0, 204, 255));
        ResepDokter.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ResepDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/approve-invoice (1).png"))); // NOI18N
        ResepDokter.setText("Resep Dokter");
        ResepDokter.setBorderPainted(false);
        ResepDokter.setContentAreaFilled(false);
        ResepDokter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ResepDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResepDokterActionPerformed(evt);
            }
        });

        FakturPenjualan.setBackground(new java.awt.Color(0, 204, 255));
        FakturPenjualan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        FakturPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/invoice.png"))); // NOI18N
        FakturPenjualan.setText("Faktur Penjualan");
        FakturPenjualan.setBorderPainted(false);
        FakturPenjualan.setContentAreaFilled(false);
        FakturPenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FakturPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakturPenjualanActionPerformed(evt);
            }
        });

        Cabang.setBackground(new java.awt.Color(0, 204, 255));
        Cabang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cabang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/pharmacy (1).png"))); // NOI18N
        Cabang.setText("Cabang");
        Cabang.setBorderPainted(false);
        Cabang.setContentAreaFilled(false);
        Cabang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Cabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CabangActionPerformed(evt);
            }
        });

        Gaji.setBackground(new java.awt.Color(0, 204, 255));
        Gaji.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/money (1).png"))); // NOI18N
        Gaji.setText("Gaji");
        Gaji.setBorderPainted(false);
        Gaji.setContentAreaFilled(false);
        Gaji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GajiActionPerformed(evt);
            }
        });

        Jabatan.setBackground(new java.awt.Color(0, 204, 255));
        Jabatan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Jabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/manager (1).png"))); // NOI18N
        Jabatan.setText("Jabatan");
        Jabatan.setBorderPainted(false);
        Jabatan.setContentAreaFilled(false);
        Jabatan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JabatanActionPerformed(evt);
            }
        });

        Tanggungan.setBackground(new java.awt.Color(0, 204, 255));
        Tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Tanggungan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/users (1).png"))); // NOI18N
        Tanggungan.setText("Tanggungan");
        Tanggungan.setBorderPainted(false);
        Tanggungan.setContentAreaFilled(false);
        Tanggungan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggunganActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 32)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/medicine (1).png"))); // NOI18N
        jLabel2.setText("Pharmacy");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Konsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Obat, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResepDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FakturPenjualan)
                            .addComponent(Cabang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gaji, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(Home)
                .addGap(18, 18, 18)
                .addComponent(Karyawan)
                .addGap(18, 18, 18)
                .addComponent(Supplier)
                .addGap(18, 18, 18)
                .addComponent(Konsumen)
                .addGap(18, 18, 18)
                .addComponent(Obat)
                .addGap(18, 18, 18)
                .addComponent(ResepDokter)
                .addGap(18, 18, 18)
                .addComponent(FakturPenjualan)
                .addGap(18, 18, 18)
                .addComponent(Cabang)
                .addGap(18, 18, 18)
                .addComponent(Gaji)
                .addGap(18, 18, 18)
                .addComponent(Jabatan)
                .addGap(18, 18, 18)
                .addComponent(Tanggungan)
                .addGap(88, 88, 88))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(692, Short.MAX_VALUE)))
        );

        tabel_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tabel_tanggungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tanggal Lahir", "Jenis Kelamin", "Hubungan", "ID Karyawan"
            }
        ));
        tabel_tanggungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_tanggunganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_tanggungan);

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        nama1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama1.setForeground(new java.awt.Color(204, 204, 204));
        nama1.setText("Nama");

        ttl_tanggungan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttl_tanggungan1.setForeground(new java.awt.Color(204, 204, 204));
        ttl_tanggungan1.setText("Tanggal Lahir");

        jk1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jk1.setForeground(new java.awt.Color(204, 204, 204));
        jk1.setText("Jenis Kelamin");

        status1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        status1.setForeground(new java.awt.Color(204, 204, 204));
        status1.setText("Hubungan");

        txt6.setBackground(new java.awt.Color(36, 47, 65));
        txt6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt6.setForeground(new java.awt.Color(204, 204, 204));
        txt6.setText("Enter Nama");
        txt6.setBorder(null);
        txt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt6MouseClicked(evt);
            }
        });

        txt7.setBackground(new java.awt.Color(36, 47, 65));
        txt7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt7.setForeground(new java.awt.Color(204, 204, 204));
        txt7.setBorder(null);

        txt8.setBackground(new java.awt.Color(36, 47, 65));
        txt8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt8.setForeground(new java.awt.Color(204, 204, 204));
        txt8.setBorder(null);

        txt9.setBackground(new java.awt.Color(36, 47, 65));
        txt9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt9.setForeground(new java.awt.Color(204, 204, 204));
        txt9.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Data Tanggungan");

        search_karyawan.setBackground(new java.awt.Color(97, 212, 195));
        search_karyawan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search_karyawan.setText("Search");
        search_karyawan.setBorder(null);
        search_karyawan.setBorderPainted(false);
        search_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_karyawanActionPerformed(evt);
            }
        });

        update_tanggungan.setBackground(new java.awt.Color(97, 212, 195));
        update_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update_tanggungan.setText("Update");
        update_tanggungan.setBorder(null);
        update_tanggungan.setBorderPainted(false);
        update_tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_tanggunganActionPerformed(evt);
            }
        });

        id_karyawan_tanggungan1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        id_karyawan_tanggungan1.setForeground(new java.awt.Color(204, 204, 204));
        id_karyawan_tanggungan1.setText("ID Karyawan");

        txt10.setBackground(new java.awt.Color(36, 47, 65));
        txt10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt10.setForeground(new java.awt.Color(204, 204, 204));
        txt10.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        delete_tanggungan.setBackground(new java.awt.Color(97, 212, 195));
        delete_tanggungan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        delete_tanggungan.setText("Delete");
        delete_tanggungan.setBorder(null);
        delete_tanggungan.setBorderPainted(false);
        delete_tanggungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_tanggunganActionPerformed(evt);
            }
        });

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jk1)
                                    .addComponent(ttl_tanggungan1)
                                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_karyawan_tanggungan1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(update_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(delete_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator15)
                                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(search_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttl_tanggungan1))
                .addGap(3, 3, 3)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jk1))
                .addGap(4, 4, 4)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status1))
                .addGap(4, 4, 4)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karyawan_tanggungan1))
                .addGap(4, 4, 4)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_tanggungan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_tanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_tanggunganActionPerformed
        // TODO add your handling code here:
        txt1.setText(null);
        txt2.setText(null);
        txt3.setText(null);
        txt4.setText(null);
        txt5.setText(null);        
    }//GEN-LAST:event_reset_tanggunganActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home hh = new Home();
        try {
            this.dispose();
            hh.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_HomeActionPerformed

    private void KaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaryawanActionPerformed
        // TODO add your handling code here:
        Karyawan_data kd= new Karyawan_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KaryawanActionPerformed

    private void SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierActionPerformed
        // TODO add your handling code here:
        Supplier_data sd = new Supplier_data();
        try {
            this.dispose();
            sd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SupplierActionPerformed

    private void KonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonsumenActionPerformed
        // TODO add your handling code here:
        Konsumen_data kd = new Konsumen_data();
        try {
            this.dispose();
            kd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_KonsumenActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
        // TODO add your handling code here:
        Obat_data od = new Obat_data();
        try {
            this.dispose();
            od.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ObatActionPerformed

    private void ResepDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResepDokterActionPerformed
        // TODO add your handling code here:
        ResepDokter_data rd = new ResepDokter_data();
        try {
            this.dispose();
            rd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ResepDokterActionPerformed

    private void FakturPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakturPenjualanActionPerformed
        // TODO add your handling code here:
        FakturPenjualan_data fd = new FakturPenjualan_data();
        try {
            this.dispose();
            fd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_FakturPenjualanActionPerformed

    private void CabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CabangActionPerformed
        // TODO add your handling code here:
        Cabang_data cd = new Cabang_data();
        try {
            this.dispose();
            cd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CabangActionPerformed

    private void GajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GajiActionPerformed
        // TODO add your handling code here:
        Gaji_data gd = new Gaji_data();
        try {
            this.dispose();
            gd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_GajiActionPerformed

    private void JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JabatanActionPerformed
        // TODO add your handling code here:
        Jabatan_data jd = new Jabatan_data();
        try {
            this.dispose();
            jd.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JabatanActionPerformed

    private void TanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggunganActionPerformed
        // TODO add your handling code here:
        Tanggungan_data td = new Tanggungan_data();
        try {
            this.dispose();
            td.show();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_TanggunganActionPerformed

    private void search_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_karyawanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery(" SELECT * FROM tanggungan WHERE nama = '"+ txt6.getText()+"'"); 
            if (rs.next()){
                String i = txt6.getText();
                String a = rs.getString("ttl");
                String b = rs.getString("JK");
                String c = rs.getString("hubungan");
                String d = rs.getString("id_karyawan");                 
                txt7.setText(a);
                txt8.setText(b);
                txt9.setText(c);
                txt10.setText(d);
                txt6.getText();
            } else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "Invalid Nama");
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_search_karyawanActionPerformed

    private void input_tanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tanggunganActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            String sql = " insert into tanggungan(nama,ttl,JK,hubungan,id_karyawan) values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txt1.getText());
            pst.setString(2, txt2.getText());
            pst.setString(3, txt3.getText());
            pst.setString(4, txt4.getText());
            pst.setString(5, txt5.getText());  
            pst.execute();            
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            DefaultTableModel model = (DefaultTableModel)tabel_tanggungan.getModel();
            model.setRowCount(0);
            show_tanggungan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertion Failed");
        }
    }//GEN-LAST:event_input_tanggunganActionPerformed

    private void update_tanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_tanggunganActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("update tanggungan set ttl = '"+txt7.getText()+
                     "',JK = '"+txt8.getText()+
                     "',hubungan = '"+txt9.getText()+
                    "',id_karyawan = '"+txt10.getText()+ 
                     "' WHERE nama = '"+txt6.getText()+"'");             
             if(rs.next()){                
               String i = txt6.getText();
                String a = rs.getString("ttl date");
                String b = rs.getString("JK");
                String c = rs.getString("hubungan");
                String d = rs.getString("id_karyawan");                
                txt7.setText(a);
                txt8.setText(b);
                txt9.setText(c);
                txt10.setText(d);
                txt6.getText();               
             }            
             DefaultTableModel model = (DefaultTableModel)tabel_tanggungan.getModel(); 
             model.setRowCount(0);
             show_tanggungan();
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Updated");
        }
    }//GEN-LAST:event_update_tanggunganActionPerformed

    private void delete_tanggunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_tanggunganActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=signup;user=sa;password=1sampai10";
            con = DriverManager.getConnection(url);
            java.sql.Statement st = con.createStatement();
            rs = st.executeQuery("delete tanggungan WHERE nama = '"+ txt6.getText()+"'");
            txt7.setText(null);
            txt8.setText(null);
            txt9.setText(null);
            txt10.setText(null);
            txt6.setText(null); 
            DefaultTableModel model = (DefaultTableModel)tabel_tanggungan.getModel();
            model.setRowCount(0);
            show_tanggungan();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Deleted");
        }
    }//GEN-LAST:event_delete_tanggunganActionPerformed

    private void tabel_tanggunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_tanggunganMouseClicked
        // TODO add your handling code here:
        int i = tabel_tanggungan.getSelectedRow();
        TableModel model = tabel_tanggungan.getModel();
        txt6.setText(model.getValueAt(i,0).toString());
        txt7.setText(model.getValueAt(i,1).toString());
        txt8.setText(model.getValueAt(i,2).toString());
        txt9.setText(model.getValueAt(i,3).toString());
        txt10.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_tabel_tanggunganMouseClicked

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        // TODO add your handling code here:
        txt1.setText("");
    }//GEN-LAST:event_txt1MouseClicked

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        // TODO add your handling code here:
        txt2.setText("");
    }//GEN-LAST:event_txt2MouseClicked

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        // TODO add your handling code here:
        txt3.setText("");
    }//GEN-LAST:event_txt3MouseClicked

    private void txt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MouseClicked
        // TODO add your handling code here:
        txt4.setText("");
    }//GEN-LAST:event_txt4MouseClicked

    private void txt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt5MouseClicked
        // TODO add your handling code here:
        txt5.setText("");
    }//GEN-LAST:event_txt5MouseClicked

    private void txt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt6MouseClicked
        // TODO add your handling code here:
        txt6.setText("");
    }//GEN-LAST:event_txt6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tanggungan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tanggungan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tanggungan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tanggungan_data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tanggungan_data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cabang;
    private javax.swing.JButton FakturPenjualan;
    private javax.swing.JButton Gaji;
    private javax.swing.JButton Home;
    private javax.swing.JButton Jabatan;
    private javax.swing.JButton Karyawan;
    private javax.swing.JButton Konsumen;
    private javax.swing.JButton Obat;
    private javax.swing.JButton ResepDokter;
    private javax.swing.JButton Supplier;
    private javax.swing.JButton Tanggungan;
    private javax.swing.JButton delete_tanggungan;
    private javax.swing.JLabel id_karyawan_tanggungan;
    private javax.swing.JLabel id_karyawan_tanggungan1;
    private javax.swing.JButton input_tanggungan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jk;
    private javax.swing.JLabel jk1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JButton reset_tanggungan;
    private javax.swing.JButton search_karyawan;
    private javax.swing.JLabel status;
    private javax.swing.JLabel status1;
    private javax.swing.JTable tabel_tanggungan;
    private javax.swing.JLabel ttl_tanggungan;
    private javax.swing.JLabel ttl_tanggungan1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JButton update_tanggungan;
    // End of variables declaration//GEN-END:variables
}
